

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanlydienSinhvien
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class quanlydiemSinhVienEntities : DbContext
{
    public quanlydiemSinhVienEntities()
        : base("name=quanlydiemSinhVienEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<hocky> hockies { get; set; }

    public virtual DbSet<ketquahoctap> ketquahoctaps { get; set; }

    public virtual DbSet<lophoc> lophocs { get; set; }

    public virtual DbSet<monhoc> monhocs { get; set; }

    public virtual DbSet<sinhvien> sinhviens { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

}

}

