
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanlydienSinhvien
{

using System;
    using System.Collections.Generic;
    
public partial class sinhvien
{

    public sinhvien()
    {

        this.ketquahoctaps = new HashSet<ketquahoctap>();

    }


    public string mssv { get; set; }

    public string hovaten { get; set; }

    public string gioitinh { get; set; }

    public string sdt { get; set; }

    public string email { get; set; }

    public Nullable<int> lophoc_id { get; set; }

    public Nullable<System.DateTime> ngaysinh { get; set; }



    public virtual ICollection<ketquahoctap> ketquahoctaps { get; set; }

    public virtual lophoc lophoc { get; set; }

}

}
